### PR TITLE
chore(project): add dmn-js migration example

### LINKED ISSUE #464: Publish example that shows how to consume DMN 1.1 and DMN 1.2 files
__What should we do?__

An example should clearly demonstrate how to consume DMN 1.1 and DMN 1.2 files with the tool.

That example should be published in our [examples repository](https://github.com/bpmn-io/dmn-js-examples).

__Why should we do it?__

Because people need to learn about how to transition between dmn-js 7.x and dmn-js 8.0.

### PR DESCRIPTION
**Pull request by philippfromme**
* add dmn-compatibility example

Closes bpmn-io/dmn-js#464

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
One proposal:

* Could we separate creating the example from updating all other examples?

One question:

* `dmn-js-migration` as an example sounds a little meaningless to me, can we use something like DMN 1.1 compatibility (or `dmn-compat`) as a name? That is what we're showcasing: How to build a tool that is capable of consuming older DMN files.

**Comment by nikku** [comment]
Ready for second round of review?

**Comment by philippfromme** [comment]
Yes, maybe the wording is not perfect, yet.

**Comment by nikku** [comment]
It's :finland:.

**Review by nikku — APPROVED** [review]

**Pull request merged**
